runtime: python
env: flex
entrypoint: gunicorn -b :$PORT demo.wsgi

runtime_config:
  python_version: 3.4

beta_settings:
    cloud_sql_instances: "<your-cloudsql-connection-string>" #with doble quotes

#optional
env_variables:
  DB_NAME: app #database
  DB_USER: app_user #user
  DB_PASSWORD: user123 #password 

manual_scaling:
  instances: 3
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10


